version: 2

jobs:
  publish:
    docker:
      - image: 093527149400.dkr.ecr.us-west-2.amazonaws.com/docker-builder:latest
    steps:
      - checkout
      - run: pypi_upload.sh

workflows:
  version: 2
  build-publish:
    jobs:
      - publish:
          context: prod
          filters:
            branches:
              only:
                - master
